### ISSUE TITLE
[ Feature request ] Can add view settings just like the heading plugin?

### ISSUE THREAD

**Issue by atzcl** [ckeditor/ckeditor5-highlight#25]
`heading`:
```
options: [
	{ model: 'heading1', view: 'h2', title: 'Heading 1', class: 'ck-heading_heading1' },
         .......
 ]
```

`highlight`:
```
options: [
         {
		model: 'yellowMarker',
		class: 'marker-yellow',
		title: 'Yellow marker',
		color: 'var(--ck-highlight-marker-yellow)',
		type: 'marker',
                 view: 'span',
	}
         .......
 ]
```
Or is there something else to do it?
Thanks for any answer.

**Comment by Mgsy** [comment]
Hello, first of all - I'm sorry for the late response, somehow we missed your ticket. 

Can you describe more precisely what do you want to achieve? If your case is about using `span` in the view, maybe the good idea will be using our `font color` and `font background` plugins? Please, take a look at our [documentation](https://ckeditor.com/docs/ckeditor5/latest/features/font.html#configuring-the-font-color-and-font-background-color-features).

**Comment by atzcl** [comment]
@Mgsy thank you for your reply，` Font ` plugin does meet my needs 😁😁
