### ISSUE TITLE
Can I use this in combination with Neos 3.3?

### ISSUE THREAD

**Issue by justin-s26** [ckeditor/ckeditor5-highlight#26]
Hello,

I'm pretty new to software development, so it would be very helpful if you could answer my question :smile: 
If so it would be also interesting, how I'll get it done. Thanks.

**Comment by Reinmar** [comment]
Hi! 

I'm afraid that a better place to ask this question would be some [Neos support channel](https://www.neos.io/docs-and-support/support.html. We don't know much about Neos and will not be able to answer your question in detail.

Also, when you'll be asking this question to Neos guys please explain what you mean by "this". Whether it's CKEditor 5 or this specific plugin.
