### ISSUE TITLE
How to custom highlight-ui like colorpicker?

### ISSUE THREAD

**Issue by superman0159** [ckeditor/ckeditor5-highlight#33]
I am using ckeditor5-vue. I want to custom highlight's ui like a colorpicker and how to do it?
![image](https://user-images.githubusercontent.com/32833804/50442947-30a02480-093c-11e9-897f-17414e6d802c.png)

Thanks for ever answer!

**Comment by oleq** [comment]
What is missing exactly? 

* The UI (grid)? 
* Some [configuration](https://ckeditor.com/docs/ckeditor5/latest/features/highlight.html#configuring-the-highlight-options) of the highlighters?
* The color picker?

**Comment by superman0159** [comment]
I want to use a color selector like in the CKEditor4 instead of CKEditor5.

**Comment by superman0159** [comment]
> What is missing exactly?
> 
> * The UI (grid)?
> * Some [configuration](https://ckeditor.com/docs/ckeditor5/latest/features/highlight.html#configuring-the-highlight-options) of the highlighters?
> * The color picker?

I want to use a color selector like in the CKEditor4 instead of CKEditor5.

**Comment by oleq** [comment]
Related https://github.com/ckeditor/ckeditor5/issues/481.

**Comment by oleq** [comment]
@superman0159 I'm closing this issue because ckeditor5-highlight is not the right repository and we'll continue the discussion https://github.com/ckeditor/ckeditor5/issues/1457.
