### ISSUE TITLE
How can i get inline style with highlight color 

### ISSUE THREAD

**Issue by xwillmadeit** [ckeditor/ckeditor5-highlight#35]
With the default highlight setting i get the editor data like this

`<p>Hello from <mark class="pen-red">CKEditor 5!</mark></p>`

How can i get the editor data like this

`<p>Hello from <mark style="color: red;">CKEditor 5!</mark></p>`

The editor data might be used in other project，but i don't have 'pen-red' style defined in that project, with inline color it will work.

**Comment by jodator** [comment]
Hi @xwillmadeit you can do it by overriding default conversion configuration:

```js
class InlineHighlighters extends Plugin {
	init() {
		const editor = this.editor;

		// Base conversion definition.
		const converterDefinition = {
			model: {
				key: 'highlight',
				values: []
			},
			view: {},
			converterPriority: 'high'
		};

		// Get highlight configuration options:
		const options = editor.config.get( 'highlight.options' );

		// Build conversion definition for configured options.
		for ( const option of options ) {
			// Define which model values are recognized:
			converterDefinition.model.values.push( option.model );

			// Define how those values are converted:
			converterDefinition.view[ option.model ] = {
				name: 'mark', // The same as in default converter.
				// Additional style attribute on <mark> element.
				styles: {
					color: option.color
				},
				classes: option.class // The same as in default converter.
			};
		}

		// Override the downcast conversion only:
		editor.conversion.for( 'downcast' ).attributeToElement( converterDefinition );
	}
}
```

Then editor must be run with

1. Added InlineHighlighters plugin
2. [Changed configuration](https://ckeditor.com/docs/ckeditor5/latest/features/highlight.html#inline-color-definitions)

```js
ClassicEditor
	.create( document.querySelector( '#editor' ), {
		plugins: [ ArticlePluginSet, Highlight, InlineHighlighters ],
		toolbar: [
			'heading', '|', 'highlight', 'bold', 'italic', 'link', 'bulletedList', 'numberedList',
			'blockQuote', 'undo', 'redo'
		],
		highlight: {
			options: [
				{
					model: 'yellowMarker',
					class: 'marker-yellow',
					title: 'Yellow marker',
					color: 'yellow',
					type: 'marker'
				},
				{
					model: 'greenMarker',
					class: 'marker-green',
					title: 'Green marker',
					color: 'green',
					type: 'marker'
				}
			]
		}
	} );
```

This will output markers compatible with default CKEditor5 highlighters as well as with the other project and will work with the toolbar nicely:

![selection_168](https://user-images.githubusercontent.com/247363/51596451-4aac3300-1ef9-11e9-8a4c-9102c1223ca3.png)

---

Alternatively if you're not interested in compatibility with default CKEditor 5 converters you can just override them:
```js
class InlineHighlighters extends Plugin {
	init() {
		const editor = this.editor;

		// Base conversion definition.
		const converterDefinition = {
			model: {
				key: 'highlight',
				values: []
			},
			view: {},
			converterPriority: 'high'
		};

		// Get highlight configuration options:
		const options = editor.config.get( 'highlight.options' );

		// Build conversion definition for configured options.
		for ( const option of options ) {
			// Define which model values are recognized:
			converterDefinition.model.values.push( option.model );

			// Define how those values are converted:
			converterDefinition.view[ option.model ] = {
				name: 'mark', // The same as in default converter.
				// Additional style attribute on <mark> element.
				styles: {
					color: option.color,
					// Override browser styles of background-color of <mark> element.
					background: 'none'
				}
			};
		}

		// Override the downcast & upcast conversion:
		editor.conversion.attributeToElement( converterDefinition );
	}
}
```

![selection_169](https://user-images.githubusercontent.com/247363/51596807-11c08e00-1efa-11e9-9af8-ab0991a51d40.png)

**Comment by moyuanhuang** [comment]
@jodator Thanks that's really helpful!

I wonder why these code didn't make it into the package? It'd be really nice if we can pass in the `style` key as a highlight option and then the plugin just consumes it and renders elements that are compatible with other parts of the application.

**Comment by gaurav2887** [comment]
@jodator @moyuanhuang - I am trying to make this working with my Angular 5 code. I am using DecoupledEditor and I do not see an option of getting Highlight options using this code:

 `this.editor.config.get('highlight.options')`

My code:

`
public editor = DecoupledEditor;


	public config = {
		plugins: [Highlight, this.inlineHighlighter() ],
		removePlugins: [ 'MediaEmbed' ],
		highlight: {
			options: [
				{
					model: 'greenMarker',
					class: 'marker-green',
					title: 'Green marker',
					color: 'rgb(25, 156, 25)',
					type: 'marker'
				},
				{
					model: 'yellowMarker',
					class: 'marker-yellow',
					title: 'Yellow marker',
					color: '#cac407',
					type: 'marker'
				},
				{
					model: 'redPen',
					class: 'pen-red',
					title: 'Red pen',
					color: 'hsl(343, 82%, 58%)',
					type: 'pen'
				}
			]
		}
	};

inlineHighlighter() {
		console.log('inlineHighlighter called');
		// Base conversion definition.
		const converterDefinition = {
			model: {
				key: 'highlight',
				values: []
			},
			view: {},
			converterPriority: 'high'
		};
		
		// Get highlight configuration options:
		const options = this.editor.config.get('highlight.options');

		// Build conversion definition for configured options.
		for (const option of options) {
			// Define which model values are recognized:
			converterDefinition.model.values.push(option.model);

			// Define how those values are converted:
			converterDefinition.view[option.model] = {
				name: 'mark', // The same as in default converter.
				// Additional style attribute on <mark> element.
				styles: {
					color: option.color
				},
				classes: option.class // The same as in default converter.
			};
		}

		// Override the downcast conversion only:
		this.editor.conversion.for('downcast').attributeToElement(converterDefinition);
	}
`

**Comment by jodator** [comment]
In order to use function as a plugin you have to pass its name not call it:

```js
 config = {
	plugins: [Highlight, inlineHighlighter ],
	removePlugins: [ 'MediaEmbed' ],
	// ...
};

function inlineHighlighter( editor ) {
	// now use editor instead of this.editor:
	editor.config.get();
}
```

**Comment by dineshvgp** [comment]
Hi @jodator, I'm also using the decoupled editor in a react project. In fact, I wanted all the plugins and toolbars to work. Additionally, I just want this inline style thing. 

To make this work, should I have to go with a custom build? or is there any easy way to achieve this?

**Comment by dineshvgp** [comment]
FYI: This is the generic component that I'm using it everywhere in my project.

```
import React from 'react';
import { FormGroup } from '@blueprintjs/core';
import CKEditor from '@ckeditor/ckeditor5-react';
import DecoupledEditor from '@ckeditor/ckeditor5-build-decoupled-document';

const RichTextEditorField = ({
  labelName,
  fieldName,
  handleChange,
  value,
  placeholder,
  className,
  disabled,
}) => (
  <FormGroup label={labelName} labelFor={fieldName} className={className}>
    <CKEditor
      onInit={editor => {
        editor.ui.view.editable.element.parentElement.insertBefore(
          editor.ui.view.toolbar.element,
          editor.ui.view.editable.element
        );
      }}
      disabled={disabled}
      placeholder={placeholder}
      onChange={handleChange}
      editor={DecoupledEditor}
      data={value}
    />
  </FormGroup>
);
export default RichTextEditorField;
```
