### ISSUE TITLE
[Docs] Add information about removing highlight to feature guid

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor5-highlight#39]
There should be clear information that:
> If the selection is collapsed inside a text with the highlight attribute, the command will remove the attribute from the entire range of that text.

Without it, the plugin behave inconsistently when there is ranged and collapsed selection.

**Comment by Reinmar** [comment]
As I commented in the PR, I don't think this is necessary. If we'll see normal users confused by this feature or if we at least thing they may be really confused by it, we should change the feature, not document that quirky behaviour.
