### ISSUE TITLE
[feature] higlight only editing

### ISSUE THREAD

**Issue by MuTaToR08** [ckeditor/ckeditor5-highlight#42]
I want to highlight errors. And I would not want the user to get markup markers. Is it possible to remove all from document when transforming from view to html?

**Comment by Mgsy** [comment]
Hello, I'm not sure if I understand what do you try to achieve. Can you explain it more precisely and give some examples?

**Comment by MuTaToR08** [comment]
I have variables in the template, and I want to highlight them if they were entered with an error, BUT the highlighting code should not get into the template engine.

**Comment by jodator** [comment]
It sounds like a use case for [markers](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_markercollection-Marker.html). Basically you only want them to be visible in the [editing pipeline](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/architecture/editing-engine.html#editing-pipeline) and do not convert them for the [data pipeline](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/architecture/editing-engine.html#data-pipeline) (ie. when using `editor.getData()`).
